packages:
    # 所有在 packages 子目录下的 packages
    -   'packages/**'
    # 所有在 clients 子目录下的 packages
    -   'clients/**'
    # 不包括在 test 文件夹下
    -   '!**/test/**'

catalog:
    '@types/node': ^22.13.14
    mitt: ^3.0.1
    sass-embedded: ^1.86.0
    typescript: ^5.8.2
    unocss: ^66.0.0
    unplugin-auto-import: ^19.1.2
    vite: ^6.2.1
    vite-hot-client: ^2.0.4
    vite-plugin-dts: ^4.5.3
    vue: ^3.5.13
    vue-router: ^4.5.0
